Feature/bokeh plots
IDinsight/ask-a-question pull request #440
Opened 2024-09-17 20:30 UTC by markbotterill

Reviewer: @sidravi1 @amiraliemami 
Estimate: 1-2 hours

---

## Ticket

Fixes: [JIRA_TICKET_LINK](https://idinsight.atlassian.net/jira/software/c/projects/AAQ/boards/43/backlog?selectedIssue=AAQ-788)

## Description

Adds topic modeling visualization to the front end

### Changes made

Topic modeling pipeline now writes to Redis during running
Front end pulls out this new Json stored in the Redis and renders interactive Bokeh with it

### Future Tasks (optional)

Improve aesthetics

## How has this been tested?

Runs locally + passes tests

## To-do before merge (optional)

## Checklist

Fill with `x` for completed. 

- [ x] My code follows the style guidelines of this project
- [ x] I have reviewed my own code to ensure good quality
- [ x] I have tested the functionality of my code to ensure it works as intended
- [x ] I have resolved merge conflicts

(Delete any items below that are not relevant)
- [ ] I have updated the automated tests
- [ ] I have updated the scripts in `scripts/`
- [ ] I have updated the requirements
- [ ] I have updated the README file
- [ ] I have updated affected documentation
- [ ] I have added a blogpost in Latest Updates
- [ ] I have updated the CI/CD scripts in `.github/workflows/`
- [ ] I have updated the Terraform code

2024-09-23 12:40 UTC, amiraliemami reviewed
Leaving mid-way comments, thanks!!

2024-09-25 11:05 UTC, amiraliemami requested changes
Awesome work man, looks great!

Pls add the timeout required and reorder the components as below, thanks!

<img width="824" alt="image" src="https://github.com/user-attachments/assets/65a546e4-b21f-46d5-8de3-70af028f04d6">

2024-10-01 15:47 UTC, markbotterill commented on admin_app/src/app/dashboard/components/insights/Bokeh.tsx
> +          )}
@amiraliemami I have implemented a fix for this (see commit 95d606f) - let me know if you think it's sufficient

2024-10-01 15:55 UTC, markbotterill commented on Makefile
>  add-users-to-db:
Tried to do the whole branch w/o adding this as a commit 🤦 Must've slipped through - my bad.

2024-10-01 15:55 UTC, markbotterill commented on core_backend/app/llm_call/llm_prompts.py
> +        encounter queries that are related to something other than maternal health.
Used {context} again to avoid this loophole

2024-10-01 16:05 UTC, markbotterill commented
> Awesome work man, looks great!
> 
> Pls add the timeout required and reorder the components as below, thanks!
> 
> <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/41763233/370684740-65a546e4-b21f-46d5-8de3-70af028f04d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTI5MjcsIm5iZiI6MTcyNzc5MjYyNywicGF0aCI6Ii80MTc2MzIzMy8zNzA2ODQ3NDAtNjVhNTQ2ZTQtYjIxZi00NmQ1LThkZTMtNzBhZjAyOGYwNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAxVDE0MjM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MzU0NjJhNmMwYTQ1ZGYzOGMzNTNjMzhkNjU5OGU1MjY2YjkzODViNjQyMWQ3M2M4MTljOWVjNTU3OTIwMmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wlLigQoHT3NBLyBfaX4n48tX9Y6DKfYr9cXQ6WCOE2A">

@amiraliemami I added to the Dockerfile and removed the timeout command.

2024-10-02 12:42 UTC, suzinyou approved these changes
Works well. thank you Mark! This is amazing work

2024-10-02 12:46 UTC, suzinyou commented
> Awesome work man, looks great!
> 
> Pls add the timeout required and reorder the components as below, thanks!
> 
> <img alt="image" width="824" src="https://private-user-images.githubusercontent.com/41763233/370684740-65a546e4-b21f-46d5-8de3-70af028f04d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NzMyODksIm5iZiI6MTcyNzg3Mjk4OSwicGF0aCI6Ii80MTc2MzIzMy8zNzA2ODQ3NDAtNjVhNTQ2ZTQtYjIxZi00NmQ1LThkZTMtNzBhZjAyOGYwNGQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAyVDEyNDMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMmRjYTJkNGNlMjM0ODc0YzhmNzQxNjAxODdlYzJiMmViNGE1ZDA1ZGY2NDJlMDIzZWZjYWI4MzEzMThmZGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bE2OZkoQaxzfB_UWw7Qf_0_T4QjpHQB3zy7mcwqP96Y">

It looks like this now :) 

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/fad9c3ae-8cfc-4cec-aa96-8e3ee7881f95">

2024-10-02 12:59 UTC, markbotterill commented
Thank you @suzinyou and @amiraliemami for all the feedback + help 🙏

2024-10-02 12:59 UTC, merged